#!/usr/bin/env python3
"""Scaffold a project-local validator bundle.

The generated validator is intentionally conservative and dependency-free. It
starts with a small set of deterministic gates, then expects the project owner
to add domain-specific rules as risks become concrete.
"""

from __future__ import annotations

import argparse
import json
import stat
import sys
from pathlib import Path
from typing import Any


DOMAINS = ("generic", "content", "teaching", "pdf", "webapp", "skill", "data")


DOMAIN_RULES: dict[str, dict[str, Any]] = {
    "generic": {
        "public_globs": ["*.md", "docs/**/*.md"],
        "forbidden_public_terms": [
            {"term": "/Users/", "severity": "P1", "reason": "local absolute path leak"},
            {"term": "TODO", "severity": "P2", "reason": "unfinished marker"},
            {"term": "TBD", "severity": "P2", "reason": "unfinished marker"},
        ],
    },
    "content": {
        "public_globs": ["*.md", "docs/**/*.md", "manuscript/**/*.md"],
        "forbidden_public_terms": [
            {"term": "TODO", "severity": "P1", "reason": "unfinished editorial marker"},
            {"term": "TBD", "severity": "P1", "reason": "unfinished editorial marker"},
            {"term": "draft note", "severity": "P2", "reason": "backstage editorial language"},
            {"term": "/Users/", "severity": "P1", "reason": "local absolute path leak"},
        ],
    },
    "teaching": {
        "public_globs": ["*.md", "docs/**/*.md", "outputs/**/*.md"],
        "forbidden_public_terms": [
            {"term": "teacher-only", "severity": "P0", "reason": "student-facing leak"},
            {"term": "answer key", "severity": "P0", "reason": "student-facing answer leak"},
            {"term": "internal tactic", "severity": "P0", "reason": "internal teaching tactic leak"},
            {"term": "validator", "severity": "P2", "reason": "process language in visible handoff"},
            {"term": "/Users/", "severity": "P1", "reason": "local absolute path leak"},
        ],
    },
    "pdf": {
        "public_globs": ["*.md", "docs/**/*.md", "qa/**/*.md"],
        "forbidden_public_terms": [
            {"term": "compile only", "severity": "P1", "reason": "PDF QA must include visual evidence"},
            {"term": "unchecked", "severity": "P1", "reason": "unresolved QA state"},
            {"term": "/Users/", "severity": "P1", "reason": "local absolute path leak"},
        ],
        "manual_review_sentinels": [
            {
                "path": "qa/final_visual_review.md",
                "sentinel": "FINAL_VISUAL_REVIEW: PASS",
                "severity": "P1",
                "reason": "formal PDF handoff requires archived visual review",
            }
        ],
    },
    "webapp": {
        "public_globs": ["README.md", "docs/**/*.md", "src/**/*.{ts,tsx,js,jsx}"],
        "forbidden_public_terms": [
            {"term": "localStorageSnapshot", "severity": "P1", "reason": "raw diagnostic export risk"},
            {"term": "INTERNAL_ONLY", "severity": "P1", "reason": "internal marker leak"},
            {"term": "/Users/", "severity": "P1", "reason": "local absolute path leak"},
        ],
    },
    "skill": {
        "public_globs": ["SKILL.md", "references/**/*.md", "scripts/**/*.{py,js,sh}"],
        "required_paths": [
            {"path": "SKILL.md", "min_bytes": 120, "severity": "P0"},
        ],
        "forbidden_public_terms": [
            {"term": "TODO", "severity": "P1", "reason": "unfinished skill marker"},
            {"term": "[TODO", "severity": "P1", "reason": "unfinished skill template"},
            {"term": "/Users/", "severity": "P1", "reason": "personal path leak"},
        ],
    },
    "data": {
        "public_globs": ["README.md", "docs/**/*.md", "reports/**/*.md"],
        "forbidden_public_terms": [
            {"term": "sample looks fine", "severity": "P1", "reason": "non-executable data QA claim"},
            {"term": "unchecked", "severity": "P1", "reason": "unresolved data QA state"},
            {"term": "/Users/", "severity": "P1", "reason": "local absolute path leak"},
        ],
    },
}


VALIDATOR_TEMPLATE = r'''#!/usr/bin/env python3
"""Project validator generated by the building-validators skill.

Edit validator_rules.json first. Keep this script read-only against deliverables:
it reports issues, writes evidence, and exits non-zero on strict failures.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
from typing import Any


DEFAULT_RULES = Path(__file__).with_name("validator_rules.json")
DEFAULT_REPORT_DIR = Path(__file__).with_name("reports")


@dataclass
class Issue:
    severity: str
    code: str
    file: str
    detail: str
    line: int | None = None


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def load_rules(path: Path) -> dict[str, Any]:
    data = json.loads(read_text(path))
    if not isinstance(data, dict):
        raise ValueError("rules file must contain a JSON object")
    return data


def error_payload(root: Path, code: str, detail: str) -> dict[str, Any]:
    issue = Issue(severity="P0", code=code, file="validator_rules.json", detail=detail)
    summary = {"status": "fail", "counts": {"P0": 1}, "strict_fail_severities": ["P0", "P1"]}
    return {
        "status": "fail",
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "root": str(root),
        "summary": summary,
        "next_action": next_action_for("fail"),
        "issues": [asdict(issue)],
    }


def rel(root: Path, path: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


def add(issues: list[Issue], severity: str, code: str, file: Path | str, detail: str, line: int | None = None) -> None:
    issues.append(Issue(severity=severity, code=code, file=str(file), detail=detail, line=line))


def line_for(text: str, needle: str, ignore_case: bool = False) -> int | None:
    haystack = text.casefold() if ignore_case else text
    target = needle.casefold() if ignore_case else needle
    index = haystack.find(target)
    if index < 0:
        return None
    return text.count("\n", 0, index) + 1


def unique_paths(paths: list[Path]) -> list[Path]:
    seen: set[Path] = set()
    out: list[Path] = []
    for path in paths:
        resolved = path.resolve()
        if resolved in seen:
            continue
        seen.add(resolved)
        out.append(path)
    return out


def int_rule(value: Any, default: int, issues: list[Issue], field: str, severity: str = "P1") -> int | None:
    raw = default if value is None else value
    try:
        return int(raw)
    except (TypeError, ValueError):
        add(issues, severity, "RULE_INVALID", "validator_rules.json", f"{field} must be an integer, got {raw!r}")
        return None


def safe_rule_path(root: Path, raw_path: Any, issues: list[Issue], severity: str, field: str) -> Path | None:
    value = str(raw_path or "")
    path = Path(value)
    if not value or path.is_absolute() or ".." in path.parts:
        add(issues, severity, "RULE_PATH_OUTSIDE_ROOT", "validator_rules.json", f"{field} must be relative and stay under root: {value!r}")
        return None
    root_resolved = root.resolve()
    cursor = root_resolved
    for part in path.parts:
        cursor = cursor / part
        if cursor.is_symlink():
            add(issues, severity, "RULE_PATH_SYMLINK", "validator_rules.json", f"{field} must not traverse symlinks: {value!r}")
            return None
    resolved = (root_resolved / path).resolve()
    try:
        resolved.relative_to(root_resolved)
    except ValueError:
        add(issues, severity, "RULE_PATH_OUTSIDE_ROOT", "validator_rules.json", f"{field} resolves outside root: {value!r}")
        return None
    return resolved


def expand_glob_pattern(pattern: str) -> list[str]:
    match = re.search(r"\{([^{}]+)\}", pattern)
    if not match:
        return [pattern]
    choices = [item.strip() for item in match.group(1).split(",") if item.strip()]
    if not choices:
        return [pattern]
    expanded: list[str] = []
    for choice in choices:
        expanded.extend(
            expand_glob_pattern(pattern[: match.start()] + choice + pattern[match.end() :])
        )
    return expanded


def safe_glob_patterns(pattern: str, issues: list[Issue], severity: str = "P1") -> list[str]:
    safe: list[str] = []
    for expanded in expand_glob_pattern(pattern):
        path = Path(expanded)
        if not expanded:
            add(issues, severity, "RULE_INVALID", "validator_rules.json", "glob pattern cannot be empty")
            continue
        if path.is_absolute() or ".." in path.parts:
            add(issues, severity, "RULE_PATH_OUTSIDE_ROOT", "validator_rules.json", f"glob must be relative and stay under root: {expanded!r}")
            continue
        safe.append(expanded)
    return safe


def glob_many(root: Path, patterns: list[str], issues: list[Issue], severity: str = "P1") -> list[Path]:
    paths: list[Path] = []
    root_resolved = root.resolve()
    for pattern in patterns:
        for expanded in safe_glob_patterns(pattern, issues, severity):
            for path in root.glob(expanded):
                has_symlink_parent = False
                try:
                    rel_parts = path.relative_to(root).parts
                except ValueError:
                    rel_parts = ()
                cursor = root
                for part in rel_parts:
                    cursor = cursor / part
                    if cursor.is_symlink():
                        has_symlink_parent = True
                        break
                if has_symlink_parent:
                    add(issues, severity, "RULE_PATH_SYMLINK", rel(root, path), "globbed validator inputs must not traverse symlinks")
                    continue
                try:
                    resolved = path.resolve()
                    resolved.relative_to(root_resolved)
                except (OSError, ValueError):
                    add(issues, severity, "RULE_PATH_OUTSIDE_ROOT", rel(root, path), "globbed validator input resolves outside root")
                    continue
                if path.is_file():
                    paths.append(path)
    return unique_paths(paths)


def check_required_paths(root: Path, rules: dict[str, Any], issues: list[Issue]) -> None:
    for item in rules.get("required_paths", []):
        if not isinstance(item, dict):
            add(issues, "P1", "RULE_INVALID", "validator_rules.json", "required_paths items must be objects")
            continue
        severity = str(item.get("severity", "P0"))
        path = safe_rule_path(root, item.get("path", ""), issues, severity, "required_paths.path")
        min_bytes = int_rule(item.get("min_bytes", 1), 1, issues, "required_paths.min_bytes", severity)
        if path is None or min_bytes is None:
            continue
        if not path.exists():
            add(issues, severity, "REQUIRED_PATH_MISSING", rel(root, path), f"required path is missing: {rel(root, path)}")
            continue
        if path.is_symlink():
            add(issues, severity, "REQUIRED_PATH_SYMLINK", rel(root, path), "required path must not be a symlink")
        try:
            size = path.stat().st_size
        except OSError as exc:
            add(issues, severity, "FILE_UNREADABLE", rel(root, path), str(exc))
            continue
        if path.is_file() and size < min_bytes:
            add(issues, severity, "REQUIRED_PATH_TOO_SMALL", rel(root, path), f"size {size}B is below {min_bytes}B")


def check_expected_counts(root: Path, rules: dict[str, Any], issues: list[Issue]) -> None:
    for item in rules.get("expected_counts", []):
        if not isinstance(item, dict):
            add(issues, "P1", "RULE_INVALID", "validator_rules.json", "expected_counts items must be objects")
            continue
        pattern = str(item.get("glob", ""))
        severity = str(item.get("severity", "P1"))
        expected = int_rule(item.get("count", -1), -1, issues, "expected_counts.count", severity)
        if expected is None:
            continue
        code = str(item.get("code", "EXPECTED_COUNT_MISMATCH"))
        actual = len(glob_many(root, [pattern], issues, severity))
        if actual != expected:
            add(issues, severity, code, pattern, f"expected {expected} files for {pattern}, found {actual}")


def check_json_files(root: Path, rules: dict[str, Any], issues: list[Issue]) -> None:
    for item in rules.get("json_files", []):
        if not isinstance(item, dict):
            add(issues, "P1", "RULE_INVALID", "validator_rules.json", "json_files items must be objects")
            continue
        severity = str(item.get("severity", "P1"))
        path = safe_rule_path(root, item.get("path", ""), issues, severity, "json_files.path")
        if path is None:
            continue
        if not path.exists():
            add(issues, severity, "JSON_FILE_MISSING", rel(root, path), "configured JSON file is missing")
            continue
        try:
            payload = json.loads(read_text(path))
        except json.JSONDecodeError as exc:
            add(issues, severity, "JSON_INVALID", rel(root, path), str(exc), exc.lineno)
            continue
        except (OSError, UnicodeDecodeError) as exc:
            add(issues, severity, "FILE_UNREADABLE", rel(root, path), str(exc))
            continue
        required_fields = item.get("required_fields", [])
        if isinstance(required_fields, list) and isinstance(payload, dict):
            for field in required_fields:
                if field not in payload:
                    add(issues, severity, "JSON_REQUIRED_FIELD_MISSING", rel(root, path), f"missing field: {field}")


def check_public_forbidden_terms(root: Path, rules: dict[str, Any], issues: list[Issue]) -> None:
    public_globs_raw = rules.get("public_globs", [])
    public_globs: list[str] = []
    if not isinstance(public_globs_raw, list):
        add(issues, "P1", "RULE_INVALID", "validator_rules.json", "public_globs must be a list")
    else:
        for item in public_globs_raw:
            if not isinstance(item, str):
                add(issues, "P1", "RULE_INVALID", "validator_rules.json", "public_globs items must be strings")
                continue
            public_globs.append(item)
    public_files = glob_many(root, public_globs, issues, "P1")
    terms = []
    for item in rules.get("forbidden_public_terms", []):
        if not isinstance(item, dict):
            add(issues, "P1", "RULE_INVALID", "validator_rules.json", "forbidden_public_terms items must be objects with term/severity/reason")
            continue
        if not str(item.get("term", "")):
            add(issues, "P1", "RULE_INVALID", "validator_rules.json", "forbidden_public_terms.term cannot be empty")
            continue
        terms.append(item)
    for path in public_files:
        try:
            text = read_text(path)
        except (OSError, UnicodeDecodeError):
            continue
        folded_text = text.casefold()
        for item in terms:
            term = str(item.get("term", ""))
            if not term or term.casefold() not in folded_text:
                continue
            severity = str(item.get("severity", "P1"))
            reason = str(item.get("reason", "forbidden term in public artifact"))
            add(
                issues,
                severity,
                "PUBLIC_FORBIDDEN_TERM",
                rel(root, path),
                f"{reason}: {term!r}",
                line_for(text, term, ignore_case=True),
            )


def check_regex_rules(root: Path, rules: dict[str, Any], issues: list[Issue]) -> None:
    for item in rules.get("regex_rules", []):
        if not isinstance(item, dict):
            add(issues, "P1", "RULE_INVALID", "validator_rules.json", "regex_rules items must be objects")
            continue
        raw_patterns = item.get("globs", [])
        if not isinstance(raw_patterns, list):
            add(issues, "P1", "RULE_INVALID", "validator_rules.json", "regex_rules.globs must be a list")
            continue
        patterns = [str(value) for value in raw_patterns]
        regex = str(item.get("regex", ""))
        code = str(item.get("code", "REGEX_RULE_HIT"))
        severity = str(item.get("severity", "P2"))
        reason = str(item.get("reason", "regex rule matched"))
        if not patterns or not regex:
            add(issues, "P1", "RULE_INVALID", "validator_rules.json", "regex_rules require globs and regex")
            continue
        try:
            compiled = re.compile(regex, re.M)
        except re.error as exc:
            add(issues, severity, "RULE_INVALID", "validator_rules.json", f"regex_rules.regex is invalid: {exc}")
            continue
        for path in glob_many(root, patterns, issues, severity):
            try:
                text = read_text(path)
            except (OSError, UnicodeDecodeError):
                continue
            match = compiled.search(text)
            if match:
                add(issues, severity, code, rel(root, path), reason, line_for(text, match.group(0)))


def check_manual_review_sentinels(root: Path, rules: dict[str, Any], issues: list[Issue]) -> None:
    for item in rules.get("manual_review_sentinels", []):
        if not isinstance(item, dict):
            add(issues, "P1", "RULE_INVALID", "validator_rules.json", "manual_review_sentinels items must be objects")
            continue
        sentinel = str(item.get("sentinel", ""))
        severity = str(item.get("severity", "P1"))
        reason = str(item.get("reason", "manual review evidence missing"))
        path = safe_rule_path(root, item.get("path", ""), issues, severity, "manual_review_sentinels.path")
        if path is None:
            continue
        if not sentinel:
            add(issues, "P1", "RULE_INVALID", "validator_rules.json", "manual review sentinel cannot be empty")
            continue
        if not path.exists():
            add(issues, severity, "MANUAL_REVIEW_MISSING", rel(root, path), reason)
            continue
        try:
            text = read_text(path)
        except (OSError, UnicodeDecodeError) as exc:
            add(issues, severity, "FILE_UNREADABLE", rel(root, path), str(exc))
            continue
        if sentinel not in text:
            add(issues, severity, "MANUAL_REVIEW_SENTINEL_MISSING", rel(root, path), f"{reason}; expected {sentinel!r}")


def summarize(issues: list[Issue], rules: dict[str, Any]) -> dict[str, Any]:
    counts: dict[str, int] = {}
    for item in issues:
        counts[item.severity] = counts.get(item.severity, 0) + 1
    configured = rules.get("strict_fail_severities", ["P0", "P1", "BLOCKER", "HIGH", "FAIL"])
    strict = {str(item) for item in configured} if isinstance(configured, list) else set()
    strict.update({"P0", "P1"})
    status = "fail" if any(item.severity in strict for item in issues) else ("warn" if issues else "pass")
    return {"status": status, "counts": counts, "strict_fail_severities": sorted(strict)}


def next_action_for(status: str) -> str:
    if status == "fail":
        return "Block release or handoff until P0/P1 findings are fixed and this validator passes again."
    if status == "warn":
        return "Review warnings, then either fix them or record an accepted-warning rationale with date and owner."
    return "Proceed only to the next declared human/source/visual review step; keep this report attached to the handoff."


def validate(root: Path, rules: dict[str, Any]) -> dict[str, Any]:
    issues: list[Issue] = []
    if not root.exists() or not root.is_dir():
        add(issues, "P0", "PROJECT_ROOT_MISSING", root, "project root must exist and be a directory")
        summary = summarize(issues, rules)
        return {
            "status": summary["status"],
            "generated_at": datetime.now().isoformat(timespec="seconds"),
            "root": str(root),
            "summary": summary,
            "next_action": next_action_for(summary["status"]),
            "issues": [asdict(item) for item in issues],
        }
    check_required_paths(root, rules, issues)
    check_expected_counts(root, rules, issues)
    check_json_files(root, rules, issues)
    check_public_forbidden_terms(root, rules, issues)
    check_regex_rules(root, rules, issues)
    check_manual_review_sentinels(root, rules, issues)
    summary = summarize(issues, rules)
    return {
        "status": summary["status"],
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "root": str(root),
        "summary": summary,
        "next_action": next_action_for(summary["status"]),
        "issues": [asdict(item) for item in issues],
    }


def render_markdown(payload: dict[str, Any]) -> str:
    lines = [
        "# Validator Report",
        "",
        f"- Status: {payload['status']}",
        f"- Root: `{payload['root']}`",
        f"- Generated: {payload['generated_at']}",
        f"- Next action: {payload['next_action']}",
        "",
        "## Counts",
        "",
    ]
    counts = payload.get("summary", {}).get("counts", {})
    if counts:
        for severity, count in sorted(counts.items()):
            lines.append(f"- {severity}: {count}")
    else:
        lines.append("- No issues.")
    lines.extend(["", "## Issues", ""])
    issues = payload.get("issues", [])
    if not issues:
        lines.append("- No issues.")
    for issue in issues:
        location = issue["file"]
        if issue.get("line"):
            location += f":{issue['line']}"
        lines.append(f"- [{issue['severity']}] {issue['code']} `{location}` - {issue['detail']}")
    lines.extend(
        [
            "",
            "## Next Action",
            "",
            payload["next_action"],
            "",
            "## Handoff Rule",
            "",
            "- `pass` means the executable gates found no blocking issue.",
            "- It does not replace source review, visual QA, or domain-owner judgment.",
        ]
    )
    return "\n".join(lines) + "\n"


def write_reports(report_dir: Path, payload: dict[str, Any]) -> None:
    report_dir.mkdir(parents=True, exist_ok=True)
    (report_dir / "validator_report.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (report_dir / "validator_report.md").write_text(render_markdown(payload), encoding="utf-8")


def safe_report_dir(root: Path, report_dir: Path) -> Path:
    target = report_dir.resolve() if report_dir.is_absolute() else (root / report_dir).resolve()
    try:
        target.relative_to(root)
    except ValueError as exc:
        raise ValueError(f"--report-dir must stay under --root: {report_dir}") from exc
    return target


def run_self_test() -> None:
    with tempfile.TemporaryDirectory(prefix="project-validator-self-test-") as tmp:
        root = Path(tmp)
        rules = {
            "strict_fail_severities": ["P0", "P1"],
            "required_paths": [{"path": "public.md", "min_bytes": 10, "severity": "P0"}],
            "public_globs": ["public.md"],
            "forbidden_public_terms": [{"term": "INTERNAL_ONLY", "severity": "P0", "reason": "internal leak"}],
        }
        bad = validate(root, rules)
        assert bad["status"] == "fail", bad
        assert "next_action" in bad and bad["next_action"], bad
        (root / "public.md").write_text("Clean public handoff text.\n", encoding="utf-8")
        good = validate(root, rules)
        assert good["status"] == "pass", good
        (root / "public.md").write_text("Clean public handoff text with INTERNAL_ONLY.\n", encoding="utf-8")
        leak = validate(root, rules)
        assert leak["status"] == "fail", leak
        escaped = validate(root, {"strict_fail_severities": ["P0", "P1"], "required_paths": [{"path": "../outside.md", "severity": "P0"}]})
        assert escaped["status"] == "fail", escaped
        assert any(issue["code"] == "RULE_PATH_OUTSIDE_ROOT" for issue in escaped["issues"]), escaped


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run project validator gates.")
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--rules", type=Path, default=DEFAULT_RULES)
    parser.add_argument("--report-dir", type=Path, default=DEFAULT_REPORT_DIR)
    parser.add_argument("--no-write", action="store_true")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.self_test:
        run_self_test()
        print("self-tests passed")
        return 0
    root = args.root.resolve()
    try:
        rules = load_rules(args.rules.resolve())
    except json.JSONDecodeError as exc:
        payload = error_payload(root, "RULES_INVALID_JSON", str(exc))
        if args.json:
            print(json.dumps(payload, ensure_ascii=False, indent=2))
        else:
            print(f"status=fail issues=1")
            print(f"- [P0] RULES_INVALID_JSON validator_rules.json: {exc}")
        return 1
    except ValueError as exc:
        payload = error_payload(root, "RULES_NOT_OBJECT", str(exc))
        if args.json:
            print(json.dumps(payload, ensure_ascii=False, indent=2))
        else:
            print(f"status=fail issues=1")
            print(f"- [P0] RULES_NOT_OBJECT validator_rules.json: {exc}")
        return 1
    except OSError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    payload = validate(root, rules)
    if not root.exists() or not root.is_dir():
        if args.json:
            print(json.dumps(payload, ensure_ascii=False, indent=2))
        else:
            print(f"status={payload['status']} issues={len(payload['issues'])}")
        return 1
    try:
        report_dir = safe_report_dir(root, args.report_dir) if not args.no_write else None
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    if not args.no_write:
        assert report_dir is not None
        write_reports(report_dir, payload)
    if args.json:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    else:
        print(f"status={payload['status']} issues={len(payload['issues'])}")
        if not args.no_write:
            assert report_dir is not None
            print(f"report={report_dir / 'validator_report.md'}")
    return 1 if payload["status"] == "fail" else 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


GENERATED_TEST_TEMPLATE = r'''#!/usr/bin/env python3
from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


VALIDATOR_DIR = Path(__file__).resolve().parents[1]
VALIDATE = VALIDATOR_DIR / "validate_project.py"
RULES = VALIDATOR_DIR / "validator_rules.json"


class GeneratedValidatorTests(unittest.TestCase):
    def run_validator(self, *args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run([sys.executable, str(VALIDATE), *args], text=True, capture_output=True)

    def test_self_test_passes(self) -> None:
        result = self.run_validator("--self-test")
        self.assertEqual(result.returncode, 0, result.stderr + result.stdout)

    def test_forbidden_public_term_blocks(self) -> None:
        with tempfile.TemporaryDirectory(prefix="project-validator-") as tmp:
            root = Path(tmp)
            rules = json.loads(RULES.read_text(encoding="utf-8"))
            rules["required_paths"] = [{"path": "public.md", "min_bytes": 5, "severity": "P0"}]
            rules["public_globs"] = ["public.md"]
            rules["forbidden_public_terms"] = [{"term": "INTERNAL_ONLY", "severity": "P0", "reason": "internal leak"}]
            rules_path = root / "rules.json"
            rules_path.write_text(json.dumps(rules, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            (root / "public.md").write_text("Visible text with INTERNAL_ONLY.\n", encoding="utf-8")
            result = self.run_validator("--root", str(root), "--rules", str(rules_path), "--no-write", "--json")
            self.assertEqual(result.returncode, 1, result.stderr + result.stdout)
            payload = json.loads(result.stdout)
            self.assertEqual(payload["status"], "fail")
            self.assertIn("next_action", payload)

    def test_parent_rule_path_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory(prefix="project-validator-") as tmp:
            base = Path(tmp)
            root = base / "project"
            root.mkdir()
            (base / "outside.md").write_text("external file\n", encoding="utf-8")
            rules = {
                "strict_fail_severities": ["P0", "P1"],
                "required_paths": [{"path": "../outside.md", "min_bytes": 1, "severity": "P0"}],
                "public_globs": [],
                "forbidden_public_terms": [],
            }
            rules_path = root / "rules.json"
            rules_path.write_text(json.dumps(rules, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            result = self.run_validator("--root", str(root), "--rules", str(rules_path), "--no-write", "--json")
            self.assertEqual(result.returncode, 1, result.stderr + result.stdout)
            payload = json.loads(result.stdout)
            codes = {issue["code"] for issue in payload["issues"]}
            self.assertIn("RULE_PATH_OUTSIDE_ROOT", codes)

    def test_malformed_min_bytes_is_structured_finding(self) -> None:
        with tempfile.TemporaryDirectory(prefix="project-validator-") as tmp:
            root = Path(tmp)
            rules = {
                "strict_fail_severities": ["P0", "P1"],
                "required_paths": [{"path": "public.md", "min_bytes": "large", "severity": "P0"}],
                "public_globs": [],
                "forbidden_public_terms": [],
            }
            rules_path = root / "rules.json"
            rules_path.write_text(json.dumps(rules, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            result = self.run_validator("--root", str(root), "--rules", str(rules_path), "--no-write", "--json")
            self.assertEqual(result.returncode, 1, result.stderr + result.stdout)
            payload = json.loads(result.stdout)
            codes = {issue["code"] for issue in payload["issues"]}
            self.assertIn("RULE_INVALID", codes)


if __name__ == "__main__":
    unittest.main()
'''


README_TEMPLATE = """# Project Validator

Generated by the `building-validators` skill.

## Run

```bash
python3 qa/validator/validate_project.py --root .
python3 qa/validator/validate_project.py --self-test
python3 qa/validator/tests/test_validate_project.py
```

## Outputs

- `qa/validator/reports/validator_report.json`
- `qa/validator/reports/validator_report.md`

## Editing Rule

Edit `validator_rules.json` before changing Python. Add one failing fixture or
self-test case for each new gate.
"""


def build_rules(domain: str) -> dict[str, Any]:
    base: dict[str, Any] = {
        "schema_version": 1,
        "domain": domain,
        "strict_fail_severities": ["P0", "P1", "BLOCKER", "HIGH", "FAIL"],
        "required_paths": [],
        "expected_counts": [],
        "json_files": [],
        "public_globs": [],
        "forbidden_public_terms": [],
        "regex_rules": [],
        "manual_review_sentinels": [],
    }
    for key, value in DOMAIN_RULES.get(domain, {}).items():
        if isinstance(value, list):
            base[key] = [*base.get(key, []), *value]
        else:
            base[key] = value
    return base


def write_file(path: Path, text: str, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"{path} exists; pass --force to overwrite")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def make_executable(path: Path) -> None:
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def resolve_out_dir(project_root: Path, out_dir: Path) -> Path:
    if out_dir.is_absolute() or ".." in out_dir.parts:
        raise ValueError(f"--out-dir must be a relative path inside project_root: {out_dir}")
    target = (project_root / out_dir).resolve()
    try:
        target.relative_to(project_root)
    except ValueError as exc:
        raise ValueError(f"--out-dir resolves outside project_root: {out_dir}") from exc
    return target


def scaffold(project_root: Path, out_dir: Path, domain: str, force: bool) -> list[Path]:
    target = resolve_out_dir(project_root, out_dir)
    rules = build_rules(domain)
    files = {
        target / "validate_project.py": VALIDATOR_TEMPLATE,
        target / "validator_rules.json": json.dumps(rules, ensure_ascii=False, indent=2) + "\n",
        target / "tests" / "test_validate_project.py": GENERATED_TEST_TEMPLATE,
        target / "README.md": README_TEMPLATE,
    }
    written: list[Path] = []
    for path, text in files.items():
        write_file(path, text, force)
        written.append(path)
    make_executable(target / "validate_project.py")
    make_executable(target / "tests" / "test_validate_project.py")
    return written


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Scaffold a project-local validator bundle.")
    parser.add_argument("project_root", nargs="?", type=Path, default=Path.cwd())
    parser.add_argument("--domain", choices=DOMAINS, default="generic")
    parser.add_argument("--out-dir", type=Path, default=Path("qa/validator"))
    parser.add_argument("--force", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    project_root = args.project_root.expanduser().resolve()
    if not project_root.exists() or not project_root.is_dir():
        print(f"ERROR: project_root must exist and be a directory: {project_root}", file=sys.stderr)
        return 1
    try:
        written = scaffold(project_root, args.out_dir, args.domain, args.force)
    except (FileExistsError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    for path in written:
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
